### PR TITLE
Replace named tokens in 'attrs.type'.

### PR DESCRIPTION
**Pull request by cpsubrian**
For example:

``` js
server.on('request', function (req, res) {
  var orig = res.end;
  res.end = function() {
    log.info('Request - :req.method :req.url (:status)', {
      status: res.statusCode,
      req: {
        method: req.method,
        url: req.url,
        // .. other req junk you want to log
      }
    });
    orig.apply(res, arguments);
  });
});
```

Might result in:

```
{type: 'Request - GET /foo.html (200)', timestamp: 123456789, req: { ... }}
```

Why do I want this?

(Pending the merge of the StdStore), I'd like to be able to 'watch' the logs in realtime only looking at the types, but later on I can look at the logs using jog's CLI with all the filtration options and whatnot.

This would allow dynamic types based on the other data without having to do any string formatting in your app code.

FYI this supports nested tokens such as `:name.first`, but does not currently support diving into Arrays at all.

### CODE REVIEW

**Comment by cpsubrian** [comment]
I'm flexible on the token syntax if you're not into `:`.

**Comment by tj** [comment]
dont want this sort of thing because the benefit of JSON logging is that you can do this sort of formatting on output instead of input

**Comment by cpsubrian** [comment]
Fair point.  To accomplish my goal I guess I would need to create a custom case-switched formatter that outputs differently depending on the `type`.  Any thoughts on how to support custom formatters in the CLI and how to distribute those formatters?

**Comment by cpsubrian** [comment]
I mean essentially its a function to pass to map, but it would be a pretty unwieldy function to pass on the command line.

**Comment by tj** [comment]
yeah the CLI stuff is somewhat limiting, but we have `.stream()` for more adhoc stuff or non-transient reporting. I started a little query language as a separate project as well

**Comment by cpsubrian** [comment]
I'll play around with some ideas in my jog2 project and see if anything seems worth exploring here.

**Pull request closed without merging**
