### PR TITLE
Removes redis dependency.

### PR DESCRIPTION
**Pull request by cpsubrian**
This updates RedisStore to only require('redis') if it needs to.  This is the same way socket.io does things so it seems reasonably standard.

### CODE REVIEW

**Comment by tj** [comment]
hmm needs a rebase i guess since i merged your other one

**Comment by cpsubrian** [comment]
Rebased and force-pushed.  Should we think about upping the version?

**Comment by tj** [comment]
nah always best to leave versioning to the author

**Comment by cpsubrian** [comment]
Sorry, meant the redis version.  But now that its not a dep the only reason it would matter is if the tests pass for 0.8.1 but would fail for 0.9.x.

**Comment by cpsubrian** [comment]
What am I smoking?  redis is 0.8.1 right now ... too many modules in my head :)

**Comment by tj** [comment]
ah :D haaha

**Pull request merged**
